#!/usr/bin/env bash
# Function to fetch DNS record and display information
function get_record() {
    local domain="$1"
    local subdomain="$2"

    # Use dig to get the DNS A record for the subdomain
    local result=$(dig +short "$subdomain.$domain" A)

    echo "The subdomain $subdomain is an A record and points to $result"
}

# If only domain parameter is provided, get records for default subdomains
if [[ -z "$2" ]]; then
    for sub in "www" "lb-01" "web-01" "web-02"; do
        get_record "$1" "$sub"
    done
else
    # If both domain and subdomain parameters are provided, get record for the specific subdomain
    get_record "$1" "$2"
fi
