#!/usr/bin/env bash
#Displays Best School 10 times but for the 9th iteration it print Hi using a while loop

counter = 0
while [ $counter -lt 10]
do
	if [ $counter -eq 9]
		echo "Hi"
	fi
	echo "Best School"
	((counter++))
done
