#!/usr/bin/env bash
#Loops from 1 to 10 and prints:
# "bad luck" for the fourth iteration
# "good luck" for the eightj iteration
# "Best school" for other iterations

counter = 0

while [ $counter -lt 10]
	if [ $counter -eq 3]
	then
		echo "bad luck"
	elif [counter -eq 7]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done	
