#!/bin/bash

# List the content of the current directory
for file in *; do
    # Use awk to split the filename and print the part after the first dash
    echo "$file" | awk -F'-' '{ if (NF > 1) { $1=""; print $0 } else { print $0 } }' | sed 's/^ //'
done
