#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.new

# Check if localhost entry exists and modify/add
grep -q "^127.0.0.1\s\+localhost" /etc/hosts && sed -i "s/^127.0.0.1\s\+localhost/127.0.0.2 localhost/" /etc/hosts || echo "127.0.0.2 localhost" >> /etc/hosts.new

# Add/Modify facebook.com entry
grep -q "^.*\s\+facebook.com" /etc/hosts && sed -i "s/^.*\s\+facebook.com/8.8.8.8 facebook.com/" /etc/hosts || echo "8.8.8.8 facebook.com" >> /etc/hosts.new
cp -f ~/hosts.new /etc/hosts
