#!/usr/bin/env bash
#Bash script to configure nginx to be listening on all active IPs on port 8080

if ! id -u nginx &> /dev/null
then
    useradd -r -s /sbin/nologin nginx
fi

chown -R nginx:nginx /var/lib/nginx  # Change ownership of nginx directories
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf  # Update nginx.conf

